spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=osahaneat;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

jwt:
  privateKey : IyRGc7W/72XOExYsw1MWW9riPBwzOnodqDpOlqQAL5g=
fileUpload:
  rootPath: C:\Users\Admin\OneDrive - ptit.edu.vn\Desktop\uploads
logging:
  level:
    org.springframework: info
    org.hibernate: info

